services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: yggdrasil-frontend
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://host.docker.internal:8888
      - DOCKER_ENV=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm run dev
    restart: unless-stopped
