services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: yggdrasil-frontend
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
      - playwright-cache:/root/.cache/ms-playwright
    environment:
      - PUBLIC_API_URL=http://localhost:8888
      - DOCKER_ENV=true
    command: npm run dev
    restart: unless-stopped

volumes:
  playwright-cache:
